### ISSUE TITLE
Lazy loading of ERA5 observations for Google Cloud Platform

### ISSUE THREAD

**Issue by kysolvik** [StevePny/DataAssimBench#52]
**Problem:** Currently to generate observations from ERA5 on GCP, we have to download all the data (for a specified window in time and space) into a Data object, and then run an observer on that object. There's no way to generate observations from the ERA5 data without downloading the fully region/time-window first.

**Possible solution:** By interfacing with xarray, we could sample times/locations and load only the data we need.

**Comment by kysolvik** [comment]
This has been solved with the xarray updates in dev/xarray_base. Once that's merged we can close this.

**Comment by StevePny** [comment]
@kysolvik is this resolved by #56 ?

**Comment by kysolvik** [comment]
@StevePny Yes, closing
