### ISSUE TITLE
Convenience methods for flattening/unflattening and splitting up xarrays

### ISSUE THREAD

**Issue by kysolvik** [StevePny/DataAssimBench#54]
**Problem**: Before xarray updates, we had two useful features in our Data classes:
1. Could flatten/unflatten the data by accessing .values and .values_gridded
2. Could split into train/val/test along time dim using .split_train_val_test() method.

With the xarray update, these no longer work.

**Possible solution**: Could create a "Vector" class that inherits from xarray that implements these methods. 
1. ds.to_stacked_array() and da.to_unstacked_dataset() work for flattening/unflattening, but can throw errors if you don't properly specify the variables and axes to stack. A class method could do those checks to make it easier.
2. ds.sel(time=slice(start,end)) is an easy way to split up the data. Could write a method that takes multiple slices to recreate the split_train_val_test method.

**Comment by kysolvik** [comment]
Added using accessors: https://docs.xarray.dev/en/stable/internals/extending-xarray.html

See commit: 3fdfabd

Use .to_system() and .to_gridded() for method names, but open to suggestions for better ones.

**Comment by StevePny** [comment]
@kysolvik is this resolved by #56 ?

**Comment by kysolvik** [comment]
@StevePny Yes it is. Following your advice, I used flatten() and unflatten() as the accessor method names. 

Closing the issue
